# Default values for Mario Helm chart.
image:
  repository: sevenajay/mario
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
    ephemeral-storage: 4Gi
  requests:
    cpu: 250m
    memory: 512Mi
    ephemeral-storage: 2Gi

service:
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 75
  memoryUtilization: 75
  scaleUpStabilization: 60
  scaleDownStabilization: 300

gateway:
  configcluster: central-cluster