---
# Default values for Mario Helm chart.
image:
  repository: sevenajay/mario
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
    ephemeral-storage: 4Gi
  requests:
    cpu: 250m
    memory: 512Mi
    ephemeral-storage: 2Gi

service:
  port: 80

autoscaling:
  enabled: true
  min: 1
  max: 5
  cpu: 75
  mem: 75
  upStab: 60
  downStab: 300

gateway:
  enable: false
