---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  namespace: mario
  labels:
    app: mario
spec:
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
        - name: mario
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
              memory: {{ .Values.resources.requests.memory | default "512Mi" }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeral_storage | default "2Gi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "1000Mi" }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeral_storage | default "4Gi" }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            seccompProfile:
              type: RuntimeDefault
