---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mario-hpa
  namespace: mario
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario
  minReplicas: {{.Values.autoscaling.minReplicas}}
  maxReplicas: {{.Values.autoscaling.maxReplicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.autoscaling.cpuUtilization}}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{.Values.autoscaling.scaleUpStabilization}}
    scaleDown:
      stabilizationWindowSeconds: {{.Values.autoscaling.scaleDownStabilization}}
...
