---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mario-hpa
  namespace: mario
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario
  minReplicas: {{ .Values.autoscaling.min | default 1 }}
  maxReplicas: {{ .Values.autoscaling.max | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.cpu | default 75 }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.upStab | default 60 }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.downStab | default 300 }}
