---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mario-hpa
  namespace: mario
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.cpu }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.upStab }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.downStab }}
