---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: mario-http-route
  namespace: mario
  labels:
    app: mario-service
    gateway: multi-cluster-gateway
spec:
  parentRefs:
    - kind: Gateway
      name: mario-external-gateway
      namespace: mario
  rules:
    - backendRefs:
        - group: net.gke.io
          kind: ServiceImport
          name: mario-service
          port: 80
