---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mario-network-policy
  namespace: mario
spec:
  podSelector:
    matchLabels:
      app: mario
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from Gateway API Gateway
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mario
          podSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway: mario-external-gateway
      ports:
        - protocol: TCP
          port: 80
    # Allow pod-to-pod communication within namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mario
          podSelector:
            matchLabels:
              app: mario
      ports:
        - protocol: TCP
          port: 80
  egress:
    - {}
