---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mario-network-policy
  namespace: mario
spec:
  podSelector:
    matchLabels:
      app: mario
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 80
  egress:
    - {}
