---
apiVersion: v1
kind: Service
metadata:
  name: mario-service
  namespace: mario
  annotations:
    networking.gke.io/max-rate-per-endpoint: "20"
  labels:
    app: mario
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mario
