apiVersion: v1
kind: Service
metadata:
  name: mario-service
  labels:
    app: mario
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 80
  selector:
    app: mario
